{% set version = "0.6.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-robustgasp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RobustGaSP_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RobustGaSP/RobustGaSP_{{ version }}.tar.gz
  sha256: d49148d65713a60c65549d87cc9d3e07cdeb0f6c4fc14551c78c2809e594b062

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - r-rcpp                           # [build_platform != target_platform]
    - r-nloptr                         # [build_platform != target_platform]
    - r-rcppeigen                      # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.3
    - r-rcppeigen
    - r-nloptr >=1.0.4
  run:
    - r-base
    - r-rcpp >=0.12.3
    - r-rcppeigen
    - r-nloptr >=1.0.4

test:
  commands:
    - $R -e "library('RobustGaSP')"           # [not win]
    - "\"%R%\" -e \"library('RobustGaSP')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RobustGaSP
  license: GPL-2.0-or-later
  summary: 'Robust parameter estimation and prediction of Gaussian stochastic process emulators. It allows for robust parameter estimation and prediction using Gaussian stochastic process emulator. It also implements the parallel partial Gaussian stochastic process emulator for computer model with massive outputs See the
    reference: Mengyang Gu and Jim Berger, 2016, Annals of Applied Statistics; Mengyang Gu, Xiaojing Wang and Jim Berger, 2018, Annals of Statistics.'
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thealanjason

# Package: RobustGaSP
# Type: Package
# Title: Robust Gaussian Stochastic Process Emulation
# Version: 0.6.5
# Date/Publication: 2022-06-01 07:20:08 UTC
# Authors@R: c(person(given="Mengyang",family="Gu",role=c("aut","cre"), email="mengyang@pstat.ucsb.edu"), person(given="Jesus",family="Palomo", role=c("aut"), email="jesus.palomo@urjc.es"), person(given="James",family="Berger", role="aut"))
# Maintainer: Mengyang Gu <mengyang@pstat.ucsb.edu>
# Author: Mengyang Gu [aut, cre], Jesus Palomo [aut], James Berger [aut]
# Description: Robust parameter estimation and prediction of Gaussian stochastic process emulators. It allows for robust parameter estimation and prediction using Gaussian stochastic process emulator. It also implements the parallel partial Gaussian stochastic process emulator for computer model with massive outputs See the reference: Mengyang Gu and Jim Berger, 2016, Annals of Applied Statistics; Mengyang Gu, Xiaojing Wang and Jim Berger, 2018, Annals of Statistics.
# License: GPL-2 | GPL-3
# LazyData: true
# Depends: R (>= 3.5.0), methods
# Imports: Rcpp (>= 0.12.3), nloptr (>= 1.0.4)
# LinkingTo: Rcpp, RcppEigen
# NeedsCompilation: yes
# Repository: CRAN
# Packaged: 2022-06-01 05:36:36 UTC; mengyanggu
# RoxygenNote: 5.0.1
